# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Team Ives
email: team@ives.mn
description: Team Ives, the awesome web consulting people.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ives.mn" # the base hostname & protocol for your site
twitter_username: courtneygives
github_username:  team-ives

# Build settings
markdown: kramdown
